// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_tak_protos/sbai_tak_protos/credentialed_cancel_behavior.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { String } from "../../../sbai_std_protos/string";
import { AuthenticationHeader } from "../../../sbai_tak_protos/authentication_header";

export const protobufPackage = "sbai_tak_protos";

export interface CredentialedCancelBehavior {
  authenticationHeader: AuthenticationHeader | undefined;
  internalMessage: String | undefined;
}

function createBaseCredentialedCancelBehavior(): CredentialedCancelBehavior {
  return { authenticationHeader: undefined, internalMessage: undefined };
}

export const CredentialedCancelBehavior: MessageFns<CredentialedCancelBehavior> = {
  encode(message: CredentialedCancelBehavior, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authenticationHeader !== undefined) {
      AuthenticationHeader.encode(message.authenticationHeader, writer.uint32(10).fork()).join();
    }
    if (message.internalMessage !== undefined) {
      String.encode(message.internalMessage, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CredentialedCancelBehavior {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCredentialedCancelBehavior();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authenticationHeader = AuthenticationHeader.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.internalMessage = String.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CredentialedCancelBehavior {
    return {
      authenticationHeader: isSet(object.authenticationHeader)
        ? AuthenticationHeader.fromJSON(object.authenticationHeader)
        : undefined,
      internalMessage: isSet(object.internalMessage) ? String.fromJSON(object.internalMessage) : undefined,
    };
  },

  toJSON(message: CredentialedCancelBehavior): unknown {
    const obj: any = {};
    if (message.authenticationHeader !== undefined) {
      obj.authenticationHeader = AuthenticationHeader.toJSON(message.authenticationHeader);
    }
    if (message.internalMessage !== undefined) {
      obj.internalMessage = String.toJSON(message.internalMessage);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CredentialedCancelBehavior>, I>>(base?: I): CredentialedCancelBehavior {
    return CredentialedCancelBehavior.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CredentialedCancelBehavior>, I>>(object: I): CredentialedCancelBehavior {
    const message = createBaseCredentialedCancelBehavior();
    message.authenticationHeader = (object.authenticationHeader !== undefined && object.authenticationHeader !== null)
      ? AuthenticationHeader.fromPartial(object.authenticationHeader)
      : undefined;
    message.internalMessage = (object.internalMessage !== undefined && object.internalMessage !== null)
      ? String.fromPartial(object.internalMessage)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
