// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_tak_protos/sbai_tak_protos/credentialed_boom_button_command.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { BoomButtonCommand } from "../../../sbai_control_protos/boom_button_command";
import { AuthenticationHeader } from "../../../sbai_tak_protos/authentication_header";

export const protobufPackage = "sbai_tak_protos";

export interface CredentialedBoomButtonCommand {
  authenticationHeader: AuthenticationHeader | undefined;
  internalMessage: BoomButtonCommand | undefined;
}

function createBaseCredentialedBoomButtonCommand(): CredentialedBoomButtonCommand {
  return { authenticationHeader: undefined, internalMessage: undefined };
}

export const CredentialedBoomButtonCommand: MessageFns<CredentialedBoomButtonCommand> = {
  encode(message: CredentialedBoomButtonCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authenticationHeader !== undefined) {
      AuthenticationHeader.encode(message.authenticationHeader, writer.uint32(10).fork()).join();
    }
    if (message.internalMessage !== undefined) {
      BoomButtonCommand.encode(message.internalMessage, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CredentialedBoomButtonCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCredentialedBoomButtonCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authenticationHeader = AuthenticationHeader.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.internalMessage = BoomButtonCommand.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CredentialedBoomButtonCommand {
    return {
      authenticationHeader: isSet(object.authenticationHeader)
        ? AuthenticationHeader.fromJSON(object.authenticationHeader)
        : undefined,
      internalMessage: isSet(object.internalMessage) ? BoomButtonCommand.fromJSON(object.internalMessage) : undefined,
    };
  },

  toJSON(message: CredentialedBoomButtonCommand): unknown {
    const obj: any = {};
    if (message.authenticationHeader !== undefined) {
      obj.authenticationHeader = AuthenticationHeader.toJSON(message.authenticationHeader);
    }
    if (message.internalMessage !== undefined) {
      obj.internalMessage = BoomButtonCommand.toJSON(message.internalMessage);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CredentialedBoomButtonCommand>, I>>(base?: I): CredentialedBoomButtonCommand {
    return CredentialedBoomButtonCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CredentialedBoomButtonCommand>, I>>(
    object: I,
  ): CredentialedBoomButtonCommand {
    const message = createBaseCredentialedBoomButtonCommand();
    message.authenticationHeader = (object.authenticationHeader !== undefined && object.authenticationHeader !== null)
      ? AuthenticationHeader.fromPartial(object.authenticationHeader)
      : undefined;
    message.internalMessage = (object.internalMessage !== undefined && object.internalMessage !== null)
      ? BoomButtonCommand.fromPartial(object.internalMessage)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
