// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_behavior_protos/sbai_behavior_protos/area_coverage_parameters.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sbai_behavior_protos";

export interface AreaCoverageParameters {
  laneWidthM: number;
}

function createBaseAreaCoverageParameters(): AreaCoverageParameters {
  return { laneWidthM: 0 };
}

export const AreaCoverageParameters: MessageFns<AreaCoverageParameters> = {
  encode(message: AreaCoverageParameters, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.laneWidthM !== 0) {
      writer.uint32(21).float(message.laneWidthM);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AreaCoverageParameters {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAreaCoverageParameters();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.laneWidthM = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AreaCoverageParameters {
    return { laneWidthM: isSet(object.laneWidthM) ? globalThis.Number(object.laneWidthM) : 0 };
  },

  toJSON(message: AreaCoverageParameters): unknown {
    const obj: any = {};
    if (message.laneWidthM !== 0) {
      obj.laneWidthM = message.laneWidthM;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AreaCoverageParameters>, I>>(base?: I): AreaCoverageParameters {
    return AreaCoverageParameters.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AreaCoverageParameters>, I>>(object: I): AreaCoverageParameters {
    const message = createBaseAreaCoverageParameters();
    message.laneWidthM = object.laneWidthM ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
