// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_behavior_protos/sbai_behavior_protos/behavior_status_beliefs.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { BehaviorStatus } from "../../../sbai_behavior_protos/behavior_status";

export const protobufPackage = "sbai_behavior_protos";

export interface BehaviorStatusBeliefs {
  robotId: string;
  behaviorStatusBeliefs: BehaviorStatus[];
}

function createBaseBehaviorStatusBeliefs(): BehaviorStatusBeliefs {
  return { robotId: "", behaviorStatusBeliefs: [] };
}

export const BehaviorStatusBeliefs: MessageFns<BehaviorStatusBeliefs> = {
  encode(message: BehaviorStatusBeliefs, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.robotId !== "") {
      writer.uint32(10).string(message.robotId);
    }
    for (const v of message.behaviorStatusBeliefs) {
      BehaviorStatus.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BehaviorStatusBeliefs {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBehaviorStatusBeliefs();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.robotId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.behaviorStatusBeliefs.push(BehaviorStatus.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BehaviorStatusBeliefs {
    return {
      robotId: isSet(object.robotId) ? globalThis.String(object.robotId) : "",
      behaviorStatusBeliefs: globalThis.Array.isArray(object?.behaviorStatusBeliefs)
        ? object.behaviorStatusBeliefs.map((e: any) => BehaviorStatus.fromJSON(e))
        : [],
    };
  },

  toJSON(message: BehaviorStatusBeliefs): unknown {
    const obj: any = {};
    if (message.robotId !== "") {
      obj.robotId = message.robotId;
    }
    if (message.behaviorStatusBeliefs?.length) {
      obj.behaviorStatusBeliefs = message.behaviorStatusBeliefs.map((e) => BehaviorStatus.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BehaviorStatusBeliefs>, I>>(base?: I): BehaviorStatusBeliefs {
    return BehaviorStatusBeliefs.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BehaviorStatusBeliefs>, I>>(object: I): BehaviorStatusBeliefs {
    const message = createBaseBehaviorStatusBeliefs();
    message.robotId = object.robotId ?? "";
    message.behaviorStatusBeliefs = object.behaviorStatusBeliefs?.map((e) => BehaviorStatus.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
