// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_behavior_protos/sbai_behavior_protos/line_formation_parameters.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sbai_behavior_protos";

export interface LineFormationParameters {
  separationDistanceM: number;
  /** 0 degrees is due East; counter-clockwise */
  lineYawDeg: number;
  /** Angle of robots in relation to the line */
  robotYawDeg: number;
}

function createBaseLineFormationParameters(): LineFormationParameters {
  return { separationDistanceM: 0, lineYawDeg: 0, robotYawDeg: 0 };
}

export const LineFormationParameters: MessageFns<LineFormationParameters> = {
  encode(message: LineFormationParameters, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.separationDistanceM !== 0) {
      writer.uint32(21).float(message.separationDistanceM);
    }
    if (message.lineYawDeg !== 0) {
      writer.uint32(29).float(message.lineYawDeg);
    }
    if (message.robotYawDeg !== 0) {
      writer.uint32(37).float(message.robotYawDeg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LineFormationParameters {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLineFormationParameters();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.separationDistanceM = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.lineYawDeg = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.robotYawDeg = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LineFormationParameters {
    return {
      separationDistanceM: isSet(object.separationDistanceM) ? globalThis.Number(object.separationDistanceM) : 0,
      lineYawDeg: isSet(object.lineYawDeg) ? globalThis.Number(object.lineYawDeg) : 0,
      robotYawDeg: isSet(object.robotYawDeg) ? globalThis.Number(object.robotYawDeg) : 0,
    };
  },

  toJSON(message: LineFormationParameters): unknown {
    const obj: any = {};
    if (message.separationDistanceM !== 0) {
      obj.separationDistanceM = message.separationDistanceM;
    }
    if (message.lineYawDeg !== 0) {
      obj.lineYawDeg = message.lineYawDeg;
    }
    if (message.robotYawDeg !== 0) {
      obj.robotYawDeg = message.robotYawDeg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LineFormationParameters>, I>>(base?: I): LineFormationParameters {
    return LineFormationParameters.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LineFormationParameters>, I>>(object: I): LineFormationParameters {
    const message = createBaseLineFormationParameters();
    message.separationDistanceM = object.separationDistanceM ?? 0;
    message.lineYawDeg = object.lineYawDeg ?? 0;
    message.robotYawDeg = object.robotYawDeg ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
