// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_behavior_protos/sbai_behavior_protos/navigate_to_pose_request.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { GeoPoint } from "../../../sbai_geographic_protos/geo_point";

export const protobufPackage = "sbai_behavior_protos";

export interface NavigateToPoseRequest {
  /** Unique ID for the requested behavior */
  behaviorRequestId: string;
  /** The requested behavior participant */
  participatingRobotId: string;
  /** A list of ordered GeoPoints to navigate to */
  geoPoints: GeoPoint[];
  desiredFinalYawDeg: number;
}

function createBaseNavigateToPoseRequest(): NavigateToPoseRequest {
  return { behaviorRequestId: "", participatingRobotId: "", geoPoints: [], desiredFinalYawDeg: 0 };
}

export const NavigateToPoseRequest: MessageFns<NavigateToPoseRequest> = {
  encode(message: NavigateToPoseRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.behaviorRequestId !== "") {
      writer.uint32(10).string(message.behaviorRequestId);
    }
    if (message.participatingRobotId !== "") {
      writer.uint32(18).string(message.participatingRobotId);
    }
    for (const v of message.geoPoints) {
      GeoPoint.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.desiredFinalYawDeg !== 0) {
      writer.uint32(37).float(message.desiredFinalYawDeg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NavigateToPoseRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNavigateToPoseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.behaviorRequestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.participatingRobotId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.geoPoints.push(GeoPoint.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.desiredFinalYawDeg = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NavigateToPoseRequest {
    return {
      behaviorRequestId: isSet(object.behaviorRequestId) ? globalThis.String(object.behaviorRequestId) : "",
      participatingRobotId: isSet(object.participatingRobotId) ? globalThis.String(object.participatingRobotId) : "",
      geoPoints: globalThis.Array.isArray(object?.geoPoints)
        ? object.geoPoints.map((e: any) => GeoPoint.fromJSON(e))
        : [],
      desiredFinalYawDeg: isSet(object.desiredFinalYawDeg) ? globalThis.Number(object.desiredFinalYawDeg) : 0,
    };
  },

  toJSON(message: NavigateToPoseRequest): unknown {
    const obj: any = {};
    if (message.behaviorRequestId !== "") {
      obj.behaviorRequestId = message.behaviorRequestId;
    }
    if (message.participatingRobotId !== "") {
      obj.participatingRobotId = message.participatingRobotId;
    }
    if (message.geoPoints?.length) {
      obj.geoPoints = message.geoPoints.map((e) => GeoPoint.toJSON(e));
    }
    if (message.desiredFinalYawDeg !== 0) {
      obj.desiredFinalYawDeg = message.desiredFinalYawDeg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NavigateToPoseRequest>, I>>(base?: I): NavigateToPoseRequest {
    return NavigateToPoseRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NavigateToPoseRequest>, I>>(object: I): NavigateToPoseRequest {
    const message = createBaseNavigateToPoseRequest();
    message.behaviorRequestId = object.behaviorRequestId ?? "";
    message.participatingRobotId = object.participatingRobotId ?? "";
    message.geoPoints = object.geoPoints?.map((e) => GeoPoint.fromPartial(e)) || [];
    message.desiredFinalYawDeg = object.desiredFinalYawDeg ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
