// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_behavior_protos/sbai_behavior_protos/raptor_parameters.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sbai_behavior_protos";

export interface RaptorParameters {
  outerRadiusM: number;
  innerRadiusM: number;
}

function createBaseRaptorParameters(): RaptorParameters {
  return { outerRadiusM: 0, innerRadiusM: 0 };
}

export const RaptorParameters: MessageFns<RaptorParameters> = {
  encode(message: RaptorParameters, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.outerRadiusM !== 0) {
      writer.uint32(21).float(message.outerRadiusM);
    }
    if (message.innerRadiusM !== 0) {
      writer.uint32(29).float(message.innerRadiusM);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RaptorParameters {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRaptorParameters();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.outerRadiusM = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.innerRadiusM = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RaptorParameters {
    return {
      outerRadiusM: isSet(object.outerRadiusM) ? globalThis.Number(object.outerRadiusM) : 0,
      innerRadiusM: isSet(object.innerRadiusM) ? globalThis.Number(object.innerRadiusM) : 0,
    };
  },

  toJSON(message: RaptorParameters): unknown {
    const obj: any = {};
    if (message.outerRadiusM !== 0) {
      obj.outerRadiusM = message.outerRadiusM;
    }
    if (message.innerRadiusM !== 0) {
      obj.innerRadiusM = message.innerRadiusM;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RaptorParameters>, I>>(base?: I): RaptorParameters {
    return RaptorParameters.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RaptorParameters>, I>>(object: I): RaptorParameters {
    const message = createBaseRaptorParameters();
    message.outerRadiusM = object.outerRadiusM ?? 0;
    message.innerRadiusM = object.innerRadiusM ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
