// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_behavior_protos/sbai_behavior_protos/swarm_map_data.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { TransformStamped } from "../../../sbai_geometry_protos/transform_stamped";

export const protobufPackage = "sbai_behavior_protos";

export interface SwarmMapData {
  behaviorRequestId: string;
  earthToSwarmMapTransform: TransformStamped | undefined;
  randomValue: number;
}

function createBaseSwarmMapData(): SwarmMapData {
  return { behaviorRequestId: "", earthToSwarmMapTransform: undefined, randomValue: 0 };
}

export const SwarmMapData: MessageFns<SwarmMapData> = {
  encode(message: SwarmMapData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.behaviorRequestId !== "") {
      writer.uint32(10).string(message.behaviorRequestId);
    }
    if (message.earthToSwarmMapTransform !== undefined) {
      TransformStamped.encode(message.earthToSwarmMapTransform, writer.uint32(18).fork()).join();
    }
    if (message.randomValue !== 0) {
      writer.uint32(24).int64(message.randomValue);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SwarmMapData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSwarmMapData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.behaviorRequestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.earthToSwarmMapTransform = TransformStamped.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.randomValue = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SwarmMapData {
    return {
      behaviorRequestId: isSet(object.behaviorRequestId) ? globalThis.String(object.behaviorRequestId) : "",
      earthToSwarmMapTransform: isSet(object.earthToSwarmMapTransform)
        ? TransformStamped.fromJSON(object.earthToSwarmMapTransform)
        : undefined,
      randomValue: isSet(object.randomValue) ? globalThis.Number(object.randomValue) : 0,
    };
  },

  toJSON(message: SwarmMapData): unknown {
    const obj: any = {};
    if (message.behaviorRequestId !== "") {
      obj.behaviorRequestId = message.behaviorRequestId;
    }
    if (message.earthToSwarmMapTransform !== undefined) {
      obj.earthToSwarmMapTransform = TransformStamped.toJSON(message.earthToSwarmMapTransform);
    }
    if (message.randomValue !== 0) {
      obj.randomValue = Math.round(message.randomValue);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SwarmMapData>, I>>(base?: I): SwarmMapData {
    return SwarmMapData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SwarmMapData>, I>>(object: I): SwarmMapData {
    const message = createBaseSwarmMapData();
    message.behaviorRequestId = object.behaviorRequestId ?? "";
    message.earthToSwarmMapTransform =
      (object.earthToSwarmMapTransform !== undefined && object.earthToSwarmMapTransform !== null)
        ? TransformStamped.fromPartial(object.earthToSwarmMapTransform)
        : undefined;
    message.randomValue = object.randomValue ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
