// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_behavior_protos/sbai_behavior_protos/swarm_map_consensus_data.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { SwarmMapData } from "../../../sbai_behavior_protos/swarm_map_data";

export const protobufPackage = "sbai_behavior_protos";

export interface SwarmMapConsensusData {
  robotId: string;
  swarmMapData: SwarmMapData | undefined;
}

function createBaseSwarmMapConsensusData(): SwarmMapConsensusData {
  return { robotId: "", swarmMapData: undefined };
}

export const SwarmMapConsensusData: MessageFns<SwarmMapConsensusData> = {
  encode(message: SwarmMapConsensusData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.robotId !== "") {
      writer.uint32(10).string(message.robotId);
    }
    if (message.swarmMapData !== undefined) {
      SwarmMapData.encode(message.swarmMapData, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SwarmMapConsensusData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSwarmMapConsensusData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.robotId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.swarmMapData = SwarmMapData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SwarmMapConsensusData {
    return {
      robotId: isSet(object.robotId) ? globalThis.String(object.robotId) : "",
      swarmMapData: isSet(object.swarmMapData) ? SwarmMapData.fromJSON(object.swarmMapData) : undefined,
    };
  },

  toJSON(message: SwarmMapConsensusData): unknown {
    const obj: any = {};
    if (message.robotId !== "") {
      obj.robotId = message.robotId;
    }
    if (message.swarmMapData !== undefined) {
      obj.swarmMapData = SwarmMapData.toJSON(message.swarmMapData);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SwarmMapConsensusData>, I>>(base?: I): SwarmMapConsensusData {
    return SwarmMapConsensusData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SwarmMapConsensusData>, I>>(object: I): SwarmMapConsensusData {
    const message = createBaseSwarmMapConsensusData();
    message.robotId = object.robotId ?? "";
    message.swarmMapData = (object.swarmMapData !== undefined && object.swarmMapData !== null)
      ? SwarmMapData.fromPartial(object.swarmMapData)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
