// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: sbai_geometry_protos/transform_stamped.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Header } from "../sbai_std_protos/header";
import { Transform } from "./transform";

export const protobufPackage = "sbai_geometry_protos";

export interface TransformStamped {
  header: Header | undefined;
  childFrameId: string;
  transform: Transform | undefined;
}

function createBaseTransformStamped(): TransformStamped {
  return { header: undefined, childFrameId: "", transform: undefined };
}

export const TransformStamped: MessageFns<TransformStamped> = {
  encode(message: TransformStamped, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.header !== undefined) {
      Header.encode(message.header, writer.uint32(10).fork()).join();
    }
    if (message.childFrameId !== "") {
      writer.uint32(18).string(message.childFrameId);
    }
    if (message.transform !== undefined) {
      Transform.encode(message.transform, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransformStamped {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransformStamped();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.header = Header.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.childFrameId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.transform = Transform.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransformStamped {
    return {
      header: isSet(object.header) ? Header.fromJSON(object.header) : undefined,
      childFrameId: isSet(object.childFrameId) ? globalThis.String(object.childFrameId) : "",
      transform: isSet(object.transform) ? Transform.fromJSON(object.transform) : undefined,
    };
  },

  toJSON(message: TransformStamped): unknown {
    const obj: any = {};
    if (message.header !== undefined) {
      obj.header = Header.toJSON(message.header);
    }
    if (message.childFrameId !== "") {
      obj.childFrameId = message.childFrameId;
    }
    if (message.transform !== undefined) {
      obj.transform = Transform.toJSON(message.transform);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransformStamped>, I>>(base?: I): TransformStamped {
    return TransformStamped.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransformStamped>, I>>(object: I): TransformStamped {
    const message = createBaseTransformStamped();
    message.header = (object.header !== undefined && object.header !== null)
      ? Header.fromPartial(object.header)
      : undefined;
    message.childFrameId = object.childFrameId ?? "";
    message.transform = (object.transform !== undefined && object.transform !== null)
      ? Transform.fromPartial(object.transform)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
