// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: sbai_geometry_protos/twist.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Vector3 } from "./vector3";

export const protobufPackage = "sbai_geometry_protos";

export interface Twist {
  linear: Vector3 | undefined;
  angular: Vector3 | undefined;
}

function createBaseTwist(): Twist {
  return { linear: undefined, angular: undefined };
}

export const Twist: MessageFns<Twist> = {
  encode(message: Twist, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.linear !== undefined) {
      Vector3.encode(message.linear, writer.uint32(10).fork()).join();
    }
    if (message.angular !== undefined) {
      Vector3.encode(message.angular, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Twist {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTwist();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.linear = Vector3.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.angular = Vector3.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Twist {
    return {
      linear: isSet(object.linear) ? Vector3.fromJSON(object.linear) : undefined,
      angular: isSet(object.angular) ? Vector3.fromJSON(object.angular) : undefined,
    };
  },

  toJSON(message: Twist): unknown {
    const obj: any = {};
    if (message.linear !== undefined) {
      obj.linear = Vector3.toJSON(message.linear);
    }
    if (message.angular !== undefined) {
      obj.angular = Vector3.toJSON(message.angular);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Twist>, I>>(base?: I): Twist {
    return Twist.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Twist>, I>>(object: I): Twist {
    const message = createBaseTwist();
    message.linear = (object.linear !== undefined && object.linear !== null)
      ? Vector3.fromPartial(object.linear)
      : undefined;
    message.angular = (object.angular !== undefined && object.angular !== null)
      ? Vector3.fromPartial(object.angular)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
