// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: payload/sbai_api_protos/sbai_api_protos/boom_service.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Empty } from "../../../google/protobuf/empty";
import { BoomButtonCommand } from "../../../sbai_control_protos/boom_button_command";

export const protobufPackage = "sbai_api_protos";

export type BoomServiceService = typeof BoomServiceService;
export const BoomServiceService = {
  triggerBoom: {
    path: "/sbai_api_protos.BoomService/TriggerBoom",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: BoomButtonCommand) => Buffer.from(BoomButtonCommand.encode(value).finish()),
    requestDeserialize: (value: Buffer) => BoomButtonCommand.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
} as const;

export interface BoomServiceServer extends UntypedServiceImplementation {
  triggerBoom: handleUnaryCall<BoomButtonCommand, Empty>;
}

export interface BoomServiceClient extends Client {
  triggerBoom(
    request: BoomButtonCommand,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  triggerBoom(
    request: BoomButtonCommand,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  triggerBoom(
    request: BoomButtonCommand,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
}

export const BoomServiceClient = makeGenericClientConstructor(
  BoomServiceService,
  "sbai_api_protos.BoomService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): BoomServiceClient;
  service: typeof BoomServiceService;
  serviceName: string;
};
