// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: payload/sbai_api_protos/sbai_api_protos/navigate_to_pose_service.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Empty } from "../../../google/protobuf/empty";
import { NavigateToPoseRequest } from "../../../sbai_behavior_protos/navigate_to_pose_request";

export const protobufPackage = "sbai_api_protos";

export type NavigateToPoseServiceService = typeof NavigateToPoseServiceService;
export const NavigateToPoseServiceService = {
  navigateToPose: {
    path: "/sbai_api_protos.NavigateToPoseService/NavigateToPose",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: NavigateToPoseRequest) => Buffer.from(NavigateToPoseRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => NavigateToPoseRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
} as const;

export interface NavigateToPoseServiceServer extends UntypedServiceImplementation {
  navigateToPose: handleUnaryCall<NavigateToPoseRequest, Empty>;
}

export interface NavigateToPoseServiceClient extends Client {
  navigateToPose(
    request: NavigateToPoseRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  navigateToPose(
    request: NavigateToPoseRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  navigateToPose(
    request: NavigateToPoseRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
}

export const NavigateToPoseServiceClient = makeGenericClientConstructor(
  NavigateToPoseServiceService,
  "sbai_api_protos.NavigateToPoseService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): NavigateToPoseServiceClient;
  service: typeof NavigateToPoseServiceService;
  serviceName: string;
};
