// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: payload/sbai_api_protos/sbai_api_protos/state_change_service.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Empty } from "../../../google/protobuf/empty";
import { CortexStateUpdate } from "../../../sbai_cortex_protos/cortex_state_update";

export const protobufPackage = "sbai_api_protos";

export type ChangeStateServiceService = typeof ChangeStateServiceService;
export const ChangeStateServiceService = {
  changeState: {
    path: "/sbai_api_protos.ChangeStateService/ChangeState",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CortexStateUpdate) => Buffer.from(CortexStateUpdate.encode(value).finish()),
    requestDeserialize: (value: Buffer) => CortexStateUpdate.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
} as const;

export interface ChangeStateServiceServer extends UntypedServiceImplementation {
  changeState: handleUnaryCall<CortexStateUpdate, Empty>;
}

export interface ChangeStateServiceClient extends Client {
  changeState(
    request: CortexStateUpdate,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  changeState(
    request: CortexStateUpdate,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  changeState(
    request: CortexStateUpdate,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
}

export const ChangeStateServiceClient = makeGenericClientConstructor(
  ChangeStateServiceService,
  "sbai_api_protos.ChangeStateService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ChangeStateServiceClient;
  service: typeof ChangeStateServiceService;
  serviceName: string;
};
