// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: sbai_control_protos/boom_button_command.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { BoolValue } from "../google/protobuf/wrappers";

export const protobufPackage = "sbai_control_protos";

export interface BoomButtonCommand {
  shouldEngageButtonCommand: boolean | undefined;
}

function createBaseBoomButtonCommand(): BoomButtonCommand {
  return { shouldEngageButtonCommand: undefined };
}

export const BoomButtonCommand: MessageFns<BoomButtonCommand> = {
  encode(message: BoomButtonCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.shouldEngageButtonCommand !== undefined) {
      BoolValue.encode({ value: message.shouldEngageButtonCommand! }, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BoomButtonCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBoomButtonCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.shouldEngageButtonCommand = BoolValue.decode(reader, reader.uint32()).value;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BoomButtonCommand {
    return {
      shouldEngageButtonCommand: isSet(object.shouldEngageButtonCommand)
        ? Boolean(object.shouldEngageButtonCommand)
        : undefined,
    };
  },

  toJSON(message: BoomButtonCommand): unknown {
    const obj: any = {};
    if (message.shouldEngageButtonCommand !== undefined) {
      obj.shouldEngageButtonCommand = message.shouldEngageButtonCommand;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BoomButtonCommand>, I>>(base?: I): BoomButtonCommand {
    return BoomButtonCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BoomButtonCommand>, I>>(object: I): BoomButtonCommand {
    const message = createBaseBoomButtonCommand();
    message.shouldEngageButtonCommand = object.shouldEngageButtonCommand ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
