// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_protos/sbai_protos/battery_percentage.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sbai_protos";

export interface BatteryPercentage {
  /** Battery percentage in the range [0.0, 100.0] */
  batteryPercentage: number;
}

function createBaseBatteryPercentage(): BatteryPercentage {
  return { batteryPercentage: 0 };
}

export const BatteryPercentage: MessageFns<BatteryPercentage> = {
  encode(message: BatteryPercentage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.batteryPercentage !== 0) {
      writer.uint32(9).double(message.batteryPercentage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BatteryPercentage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBatteryPercentage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.batteryPercentage = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BatteryPercentage {
    return { batteryPercentage: isSet(object.batteryPercentage) ? globalThis.Number(object.batteryPercentage) : 0 };
  },

  toJSON(message: BatteryPercentage): unknown {
    const obj: any = {};
    if (message.batteryPercentage !== 0) {
      obj.batteryPercentage = message.batteryPercentage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BatteryPercentage>, I>>(base?: I): BatteryPercentage {
    return BatteryPercentage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BatteryPercentage>, I>>(object: I): BatteryPercentage {
    const message = createBaseBatteryPercentage();
    message.batteryPercentage = object.batteryPercentage ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
