// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_protos/sbai_protos/behavior_service.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { BoolValue } from "../../../google/protobuf/wrappers";
import { AreaCoverageRequest } from "../../../sbai_protos/area_coverage_request";
import { BehaviorControlCommand } from "../../../sbai_protos/behavior_control_command";
import { DefendRequest } from "../../../sbai_protos/defend_request";
import { LineFormationRequest } from "../../../sbai_protos/line_formation_request";
import { MultiWaypointNavigationRequest } from "../../../sbai_protos/multi_waypoint_navigation_request";
import { NavigateToPoseRequest } from "../../../sbai_protos/navigate_to_pose_request";
import { PatrolRequest } from "../../../sbai_protos/patrol_request";
import { RallyRequest } from "../../../sbai_protos/rally_request";
import { SurroundRequest } from "../../../sbai_protos/surround_request";

export const protobufPackage = "sbai_protos";

export type BehaviorServiceService = typeof BehaviorServiceService;
export const BehaviorServiceService = {
  requestAreaCoverage: {
    path: "/sbai_protos.BehaviorService/RequestAreaCoverage",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AreaCoverageRequest) => Buffer.from(AreaCoverageRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AreaCoverageRequest.decode(value),
    responseSerialize: (value: boolean | undefined) =>
      Buffer.from(BoolValue.encode({ value: value ?? false }).finish()),
    responseDeserialize: (value: Buffer) => BoolValue.decode(value).value,
  },
  requestDefend: {
    path: "/sbai_protos.BehaviorService/RequestDefend",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DefendRequest) => Buffer.from(DefendRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => DefendRequest.decode(value),
    responseSerialize: (value: boolean | undefined) =>
      Buffer.from(BoolValue.encode({ value: value ?? false }).finish()),
    responseDeserialize: (value: Buffer) => BoolValue.decode(value).value,
  },
  requestLineFormation: {
    path: "/sbai_protos.BehaviorService/RequestLineFormation",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: LineFormationRequest) => Buffer.from(LineFormationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => LineFormationRequest.decode(value),
    responseSerialize: (value: boolean | undefined) =>
      Buffer.from(BoolValue.encode({ value: value ?? false }).finish()),
    responseDeserialize: (value: Buffer) => BoolValue.decode(value).value,
  },
  requestMultiWaypointNavigation: {
    path: "/sbai_protos.BehaviorService/RequestMultiWaypointNavigation",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: MultiWaypointNavigationRequest) =>
      Buffer.from(MultiWaypointNavigationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => MultiWaypointNavigationRequest.decode(value),
    responseSerialize: (value: boolean | undefined) =>
      Buffer.from(BoolValue.encode({ value: value ?? false }).finish()),
    responseDeserialize: (value: Buffer) => BoolValue.decode(value).value,
  },
  requestNavigateToPose: {
    path: "/sbai_protos.BehaviorService/RequestNavigateToPose",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: NavigateToPoseRequest) => Buffer.from(NavigateToPoseRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => NavigateToPoseRequest.decode(value),
    responseSerialize: (value: boolean | undefined) =>
      Buffer.from(BoolValue.encode({ value: value ?? false }).finish()),
    responseDeserialize: (value: Buffer) => BoolValue.decode(value).value,
  },
  requestPatrol: {
    path: "/sbai_protos.BehaviorService/RequestPatrol",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: PatrolRequest) => Buffer.from(PatrolRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => PatrolRequest.decode(value),
    responseSerialize: (value: boolean | undefined) =>
      Buffer.from(BoolValue.encode({ value: value ?? false }).finish()),
    responseDeserialize: (value: Buffer) => BoolValue.decode(value).value,
  },
  requestRally: {
    path: "/sbai_protos.BehaviorService/RequestRally",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RallyRequest) => Buffer.from(RallyRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => RallyRequest.decode(value),
    responseSerialize: (value: boolean | undefined) =>
      Buffer.from(BoolValue.encode({ value: value ?? false }).finish()),
    responseDeserialize: (value: Buffer) => BoolValue.decode(value).value,
  },
  requestSurround: {
    path: "/sbai_protos.BehaviorService/RequestSurround",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SurroundRequest) => Buffer.from(SurroundRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => SurroundRequest.decode(value),
    responseSerialize: (value: boolean | undefined) =>
      Buffer.from(BoolValue.encode({ value: value ?? false }).finish()),
    responseDeserialize: (value: Buffer) => BoolValue.decode(value).value,
  },
  issueBehaviorCommand: {
    path: "/sbai_protos.BehaviorService/IssueBehaviorCommand",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: BehaviorControlCommand) => Buffer.from(BehaviorControlCommand.encode(value).finish()),
    requestDeserialize: (value: Buffer) => BehaviorControlCommand.decode(value),
    responseSerialize: (value: boolean | undefined) =>
      Buffer.from(BoolValue.encode({ value: value ?? false }).finish()),
    responseDeserialize: (value: Buffer) => BoolValue.decode(value).value,
  },
} as const;

export interface BehaviorServiceServer extends UntypedServiceImplementation {
  requestAreaCoverage: handleUnaryCall<AreaCoverageRequest, boolean | undefined>;
  requestDefend: handleUnaryCall<DefendRequest, boolean | undefined>;
  requestLineFormation: handleUnaryCall<LineFormationRequest, boolean | undefined>;
  requestMultiWaypointNavigation: handleUnaryCall<MultiWaypointNavigationRequest, boolean | undefined>;
  requestNavigateToPose: handleUnaryCall<NavigateToPoseRequest, boolean | undefined>;
  requestPatrol: handleUnaryCall<PatrolRequest, boolean | undefined>;
  requestRally: handleUnaryCall<RallyRequest, boolean | undefined>;
  requestSurround: handleUnaryCall<SurroundRequest, boolean | undefined>;
  issueBehaviorCommand: handleUnaryCall<BehaviorControlCommand, boolean | undefined>;
}

export interface BehaviorServiceClient extends Client {
  requestAreaCoverage(
    request: AreaCoverageRequest,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestAreaCoverage(
    request: AreaCoverageRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestAreaCoverage(
    request: AreaCoverageRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestDefend(
    request: DefendRequest,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestDefend(
    request: DefendRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestDefend(
    request: DefendRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestLineFormation(
    request: LineFormationRequest,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestLineFormation(
    request: LineFormationRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestLineFormation(
    request: LineFormationRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestMultiWaypointNavigation(
    request: MultiWaypointNavigationRequest,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestMultiWaypointNavigation(
    request: MultiWaypointNavigationRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestMultiWaypointNavigation(
    request: MultiWaypointNavigationRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestNavigateToPose(
    request: NavigateToPoseRequest,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestNavigateToPose(
    request: NavigateToPoseRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestNavigateToPose(
    request: NavigateToPoseRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestPatrol(
    request: PatrolRequest,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestPatrol(
    request: PatrolRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestPatrol(
    request: PatrolRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestRally(
    request: RallyRequest,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestRally(
    request: RallyRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestRally(
    request: RallyRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestSurround(
    request: SurroundRequest,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestSurround(
    request: SurroundRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  requestSurround(
    request: SurroundRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  issueBehaviorCommand(
    request: BehaviorControlCommand,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  issueBehaviorCommand(
    request: BehaviorControlCommand,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  issueBehaviorCommand(
    request: BehaviorControlCommand,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
}

export const BehaviorServiceClient = makeGenericClientConstructor(
  BehaviorServiceService,
  "sbai_protos.BehaviorService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): BehaviorServiceClient;
  service: typeof BehaviorServiceService;
  serviceName: string;
};
