// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_protos/sbai_protos/behavior_service.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { CancelBehaviorRequest, CancelBehaviorResponse } from "../../../sbai_protos/cancel_behavior";
import { CoverAreaRequest, CoverAreaResponse } from "../../../sbai_protos/cover_area";
import { DefendPointRequest, DefendPointResponse } from "../../../sbai_protos/defend_point";
import { FormLineRequest, FormLineResponse } from "../../../sbai_protos/form_line";
import { NavigateRouteRequest, NavigateRouteResponse } from "../../../sbai_protos/navigate_route";
import { NavigateToRequest, NavigateToResponse } from "../../../sbai_protos/navigate_to";
import { PatrolPerimeterRequest, PatrolPerimeterResponse } from "../../../sbai_protos/patrol_perimeter";
import { PauseBehaviorRequest, PauseBehaviorResponse } from "../../../sbai_protos/pause_behavior";
import { RallyToRequest, RallyToResponse } from "../../../sbai_protos/rally_to";
import { RestartBehaviorRequest, RestartBehaviorResponse } from "../../../sbai_protos/restart_behavior";
import { ResumeBehaviorRequest, ResumeBehaviorResponse } from "../../../sbai_protos/resume_behavior";
import { SurroundPointRequest, SurroundPointResponse } from "../../../sbai_protos/surround_point";

export const protobufPackage = "sbai_protos";

export type BehaviorServiceService = typeof BehaviorServiceService;
export const BehaviorServiceService = {
  coverArea: {
    path: "/sbai_protos.BehaviorService/CoverArea",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CoverAreaRequest) => Buffer.from(CoverAreaRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => CoverAreaRequest.decode(value),
    responseSerialize: (value: CoverAreaResponse) => Buffer.from(CoverAreaResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CoverAreaResponse.decode(value),
  },
  defendPoint: {
    path: "/sbai_protos.BehaviorService/DefendPoint",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DefendPointRequest) => Buffer.from(DefendPointRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => DefendPointRequest.decode(value),
    responseSerialize: (value: DefendPointResponse) => Buffer.from(DefendPointResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => DefendPointResponse.decode(value),
  },
  formLine: {
    path: "/sbai_protos.BehaviorService/FormLine",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: FormLineRequest) => Buffer.from(FormLineRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => FormLineRequest.decode(value),
    responseSerialize: (value: FormLineResponse) => Buffer.from(FormLineResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => FormLineResponse.decode(value),
  },
  navigateRoute: {
    path: "/sbai_protos.BehaviorService/NavigateRoute",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: NavigateRouteRequest) => Buffer.from(NavigateRouteRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => NavigateRouteRequest.decode(value),
    responseSerialize: (value: NavigateRouteResponse) => Buffer.from(NavigateRouteResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => NavigateRouteResponse.decode(value),
  },
  navigateTo: {
    path: "/sbai_protos.BehaviorService/NavigateTo",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: NavigateToRequest) => Buffer.from(NavigateToRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => NavigateToRequest.decode(value),
    responseSerialize: (value: NavigateToResponse) => Buffer.from(NavigateToResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => NavigateToResponse.decode(value),
  },
  patrolPerimeter: {
    path: "/sbai_protos.BehaviorService/PatrolPerimeter",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: PatrolPerimeterRequest) => Buffer.from(PatrolPerimeterRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => PatrolPerimeterRequest.decode(value),
    responseSerialize: (value: PatrolPerimeterResponse) => Buffer.from(PatrolPerimeterResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => PatrolPerimeterResponse.decode(value),
  },
  rallyTo: {
    path: "/sbai_protos.BehaviorService/RallyTo",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RallyToRequest) => Buffer.from(RallyToRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => RallyToRequest.decode(value),
    responseSerialize: (value: RallyToResponse) => Buffer.from(RallyToResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => RallyToResponse.decode(value),
  },
  surroundPoint: {
    path: "/sbai_protos.BehaviorService/SurroundPoint",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SurroundPointRequest) => Buffer.from(SurroundPointRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => SurroundPointRequest.decode(value),
    responseSerialize: (value: SurroundPointResponse) => Buffer.from(SurroundPointResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => SurroundPointResponse.decode(value),
  },
  cancelBehavior: {
    path: "/sbai_protos.BehaviorService/CancelBehavior",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CancelBehaviorRequest) => Buffer.from(CancelBehaviorRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => CancelBehaviorRequest.decode(value),
    responseSerialize: (value: CancelBehaviorResponse) => Buffer.from(CancelBehaviorResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CancelBehaviorResponse.decode(value),
  },
  pauseBehavior: {
    path: "/sbai_protos.BehaviorService/PauseBehavior",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: PauseBehaviorRequest) => Buffer.from(PauseBehaviorRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => PauseBehaviorRequest.decode(value),
    responseSerialize: (value: PauseBehaviorResponse) => Buffer.from(PauseBehaviorResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => PauseBehaviorResponse.decode(value),
  },
  restartBehavior: {
    path: "/sbai_protos.BehaviorService/RestartBehavior",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RestartBehaviorRequest) => Buffer.from(RestartBehaviorRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => RestartBehaviorRequest.decode(value),
    responseSerialize: (value: RestartBehaviorResponse) => Buffer.from(RestartBehaviorResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => RestartBehaviorResponse.decode(value),
  },
  resumeBehavior: {
    path: "/sbai_protos.BehaviorService/ResumeBehavior",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ResumeBehaviorRequest) => Buffer.from(ResumeBehaviorRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ResumeBehaviorRequest.decode(value),
    responseSerialize: (value: ResumeBehaviorResponse) => Buffer.from(ResumeBehaviorResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ResumeBehaviorResponse.decode(value),
  },
} as const;

export interface BehaviorServiceServer extends UntypedServiceImplementation {
  coverArea: handleUnaryCall<CoverAreaRequest, CoverAreaResponse>;
  defendPoint: handleUnaryCall<DefendPointRequest, DefendPointResponse>;
  formLine: handleUnaryCall<FormLineRequest, FormLineResponse>;
  navigateRoute: handleUnaryCall<NavigateRouteRequest, NavigateRouteResponse>;
  navigateTo: handleUnaryCall<NavigateToRequest, NavigateToResponse>;
  patrolPerimeter: handleUnaryCall<PatrolPerimeterRequest, PatrolPerimeterResponse>;
  rallyTo: handleUnaryCall<RallyToRequest, RallyToResponse>;
  surroundPoint: handleUnaryCall<SurroundPointRequest, SurroundPointResponse>;
  cancelBehavior: handleUnaryCall<CancelBehaviorRequest, CancelBehaviorResponse>;
  pauseBehavior: handleUnaryCall<PauseBehaviorRequest, PauseBehaviorResponse>;
  restartBehavior: handleUnaryCall<RestartBehaviorRequest, RestartBehaviorResponse>;
  resumeBehavior: handleUnaryCall<ResumeBehaviorRequest, ResumeBehaviorResponse>;
}

export interface BehaviorServiceClient extends Client {
  coverArea(
    request: CoverAreaRequest,
    callback: (error: ServiceError | null, response: CoverAreaResponse) => void,
  ): ClientUnaryCall;
  coverArea(
    request: CoverAreaRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CoverAreaResponse) => void,
  ): ClientUnaryCall;
  coverArea(
    request: CoverAreaRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CoverAreaResponse) => void,
  ): ClientUnaryCall;
  defendPoint(
    request: DefendPointRequest,
    callback: (error: ServiceError | null, response: DefendPointResponse) => void,
  ): ClientUnaryCall;
  defendPoint(
    request: DefendPointRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: DefendPointResponse) => void,
  ): ClientUnaryCall;
  defendPoint(
    request: DefendPointRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: DefendPointResponse) => void,
  ): ClientUnaryCall;
  formLine(
    request: FormLineRequest,
    callback: (error: ServiceError | null, response: FormLineResponse) => void,
  ): ClientUnaryCall;
  formLine(
    request: FormLineRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: FormLineResponse) => void,
  ): ClientUnaryCall;
  formLine(
    request: FormLineRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: FormLineResponse) => void,
  ): ClientUnaryCall;
  navigateRoute(
    request: NavigateRouteRequest,
    callback: (error: ServiceError | null, response: NavigateRouteResponse) => void,
  ): ClientUnaryCall;
  navigateRoute(
    request: NavigateRouteRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: NavigateRouteResponse) => void,
  ): ClientUnaryCall;
  navigateRoute(
    request: NavigateRouteRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: NavigateRouteResponse) => void,
  ): ClientUnaryCall;
  navigateTo(
    request: NavigateToRequest,
    callback: (error: ServiceError | null, response: NavigateToResponse) => void,
  ): ClientUnaryCall;
  navigateTo(
    request: NavigateToRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: NavigateToResponse) => void,
  ): ClientUnaryCall;
  navigateTo(
    request: NavigateToRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: NavigateToResponse) => void,
  ): ClientUnaryCall;
  patrolPerimeter(
    request: PatrolPerimeterRequest,
    callback: (error: ServiceError | null, response: PatrolPerimeterResponse) => void,
  ): ClientUnaryCall;
  patrolPerimeter(
    request: PatrolPerimeterRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: PatrolPerimeterResponse) => void,
  ): ClientUnaryCall;
  patrolPerimeter(
    request: PatrolPerimeterRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: PatrolPerimeterResponse) => void,
  ): ClientUnaryCall;
  rallyTo(
    request: RallyToRequest,
    callback: (error: ServiceError | null, response: RallyToResponse) => void,
  ): ClientUnaryCall;
  rallyTo(
    request: RallyToRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RallyToResponse) => void,
  ): ClientUnaryCall;
  rallyTo(
    request: RallyToRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RallyToResponse) => void,
  ): ClientUnaryCall;
  surroundPoint(
    request: SurroundPointRequest,
    callback: (error: ServiceError | null, response: SurroundPointResponse) => void,
  ): ClientUnaryCall;
  surroundPoint(
    request: SurroundPointRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SurroundPointResponse) => void,
  ): ClientUnaryCall;
  surroundPoint(
    request: SurroundPointRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SurroundPointResponse) => void,
  ): ClientUnaryCall;
  cancelBehavior(
    request: CancelBehaviorRequest,
    callback: (error: ServiceError | null, response: CancelBehaviorResponse) => void,
  ): ClientUnaryCall;
  cancelBehavior(
    request: CancelBehaviorRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CancelBehaviorResponse) => void,
  ): ClientUnaryCall;
  cancelBehavior(
    request: CancelBehaviorRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CancelBehaviorResponse) => void,
  ): ClientUnaryCall;
  pauseBehavior(
    request: PauseBehaviorRequest,
    callback: (error: ServiceError | null, response: PauseBehaviorResponse) => void,
  ): ClientUnaryCall;
  pauseBehavior(
    request: PauseBehaviorRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: PauseBehaviorResponse) => void,
  ): ClientUnaryCall;
  pauseBehavior(
    request: PauseBehaviorRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: PauseBehaviorResponse) => void,
  ): ClientUnaryCall;
  restartBehavior(
    request: RestartBehaviorRequest,
    callback: (error: ServiceError | null, response: RestartBehaviorResponse) => void,
  ): ClientUnaryCall;
  restartBehavior(
    request: RestartBehaviorRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RestartBehaviorResponse) => void,
  ): ClientUnaryCall;
  restartBehavior(
    request: RestartBehaviorRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RestartBehaviorResponse) => void,
  ): ClientUnaryCall;
  resumeBehavior(
    request: ResumeBehaviorRequest,
    callback: (error: ServiceError | null, response: ResumeBehaviorResponse) => void,
  ): ClientUnaryCall;
  resumeBehavior(
    request: ResumeBehaviorRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ResumeBehaviorResponse) => void,
  ): ClientUnaryCall;
  resumeBehavior(
    request: ResumeBehaviorRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ResumeBehaviorResponse) => void,
  ): ClientUnaryCall;
}

export const BehaviorServiceClient = makeGenericClientConstructor(
  BehaviorServiceService,
  "sbai_protos.BehaviorService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): BehaviorServiceClient;
  service: typeof BehaviorServiceService;
  serviceName: string;
};
