// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_protos/sbai_protos/boom_button_status.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sbai_protos";

export enum BoomButtonState {
  BOOM_BUTTON_STATE_UNSPECIFIED = 0,
  BOOM_BUTTON_STATE_ENGAGED = 1,
  BOOM_BUTTON_STATE_DISENGAGED = 2,
  UNRECOGNIZED = -1,
}

export function boomButtonStateFromJSON(object: any): BoomButtonState {
  switch (object) {
    case 0:
    case "BOOM_BUTTON_STATE_UNSPECIFIED":
      return BoomButtonState.BOOM_BUTTON_STATE_UNSPECIFIED;
    case 1:
    case "BOOM_BUTTON_STATE_ENGAGED":
      return BoomButtonState.BOOM_BUTTON_STATE_ENGAGED;
    case 2:
    case "BOOM_BUTTON_STATE_DISENGAGED":
      return BoomButtonState.BOOM_BUTTON_STATE_DISENGAGED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return BoomButtonState.UNRECOGNIZED;
  }
}

export function boomButtonStateToJSON(object: BoomButtonState): string {
  switch (object) {
    case BoomButtonState.BOOM_BUTTON_STATE_UNSPECIFIED:
      return "BOOM_BUTTON_STATE_UNSPECIFIED";
    case BoomButtonState.BOOM_BUTTON_STATE_ENGAGED:
      return "BOOM_BUTTON_STATE_ENGAGED";
    case BoomButtonState.BOOM_BUTTON_STATE_DISENGAGED:
      return "BOOM_BUTTON_STATE_DISENGAGED";
    case BoomButtonState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface BoomButtonStatus {
  boomButtonState: BoomButtonState;
}

function createBaseBoomButtonStatus(): BoomButtonStatus {
  return { boomButtonState: 0 };
}

export const BoomButtonStatus: MessageFns<BoomButtonStatus> = {
  encode(message: BoomButtonStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.boomButtonState !== 0) {
      writer.uint32(8).int32(message.boomButtonState);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BoomButtonStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBoomButtonStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.boomButtonState = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BoomButtonStatus {
    return { boomButtonState: isSet(object.boomButtonState) ? boomButtonStateFromJSON(object.boomButtonState) : 0 };
  },

  toJSON(message: BoomButtonStatus): unknown {
    const obj: any = {};
    if (message.boomButtonState !== 0) {
      obj.boomButtonState = boomButtonStateToJSON(message.boomButtonState);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BoomButtonStatus>, I>>(base?: I): BoomButtonStatus {
    return BoomButtonStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BoomButtonStatus>, I>>(object: I): BoomButtonStatus {
    const message = createBaseBoomButtonStatus();
    message.boomButtonState = object.boomButtonState ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
