// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_protos/sbai_protos/can_status.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sbai_protos";

export enum CanState {
  CAN_STATE_UNSPECIFIED = 0,
  CAN_STATE_NORMAL = 1,
  CAN_STATE_ERROR = 2,
  UNRECOGNIZED = -1,
}

export function canStateFromJSON(object: any): CanState {
  switch (object) {
    case 0:
    case "CAN_STATE_UNSPECIFIED":
      return CanState.CAN_STATE_UNSPECIFIED;
    case 1:
    case "CAN_STATE_NORMAL":
      return CanState.CAN_STATE_NORMAL;
    case 2:
    case "CAN_STATE_ERROR":
      return CanState.CAN_STATE_ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CanState.UNRECOGNIZED;
  }
}

export function canStateToJSON(object: CanState): string {
  switch (object) {
    case CanState.CAN_STATE_UNSPECIFIED:
      return "CAN_STATE_UNSPECIFIED";
    case CanState.CAN_STATE_NORMAL:
      return "CAN_STATE_NORMAL";
    case CanState.CAN_STATE_ERROR:
      return "CAN_STATE_ERROR";
    case CanState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CanStatus {
  canState: CanState;
}

function createBaseCanStatus(): CanStatus {
  return { canState: 0 };
}

export const CanStatus: MessageFns<CanStatus> = {
  encode(message: CanStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.canState !== 0) {
      writer.uint32(8).int32(message.canState);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CanStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCanStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.canState = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CanStatus {
    return { canState: isSet(object.canState) ? canStateFromJSON(object.canState) : 0 };
  },

  toJSON(message: CanStatus): unknown {
    const obj: any = {};
    if (message.canState !== 0) {
      obj.canState = canStateToJSON(message.canState);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CanStatus>, I>>(base?: I): CanStatus {
    return CanStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CanStatus>, I>>(object: I): CanStatus {
    const message = createBaseCanStatus();
    message.canState = object.canState ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
