// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_protos/sbai_protos/ecu_status.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sbai_protos";

export enum EcuState {
  ECU_STATE_UNSPECIFIED = 0,
  ECU_STATE_NORMAL = 1,
  ECU_STATE_ERROR = 2,
  UNRECOGNIZED = -1,
}

export function ecuStateFromJSON(object: any): EcuState {
  switch (object) {
    case 0:
    case "ECU_STATE_UNSPECIFIED":
      return EcuState.ECU_STATE_UNSPECIFIED;
    case 1:
    case "ECU_STATE_NORMAL":
      return EcuState.ECU_STATE_NORMAL;
    case 2:
    case "ECU_STATE_ERROR":
      return EcuState.ECU_STATE_ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EcuState.UNRECOGNIZED;
  }
}

export function ecuStateToJSON(object: EcuState): string {
  switch (object) {
    case EcuState.ECU_STATE_UNSPECIFIED:
      return "ECU_STATE_UNSPECIFIED";
    case EcuState.ECU_STATE_NORMAL:
      return "ECU_STATE_NORMAL";
    case EcuState.ECU_STATE_ERROR:
      return "ECU_STATE_ERROR";
    case EcuState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface EcuStatus {
  ecuState: EcuState;
}

function createBaseEcuStatus(): EcuStatus {
  return { ecuState: 0 };
}

export const EcuStatus: MessageFns<EcuStatus> = {
  encode(message: EcuStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ecuState !== 0) {
      writer.uint32(8).int32(message.ecuState);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EcuStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEcuStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ecuState = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EcuStatus {
    return { ecuState: isSet(object.ecuState) ? ecuStateFromJSON(object.ecuState) : 0 };
  },

  toJSON(message: EcuStatus): unknown {
    const obj: any = {};
    if (message.ecuState !== 0) {
      obj.ecuState = ecuStateToJSON(message.ecuState);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EcuStatus>, I>>(base?: I): EcuStatus {
    return EcuStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EcuStatus>, I>>(object: I): EcuStatus {
    const message = createBaseEcuStatus();
    message.ecuState = object.ecuState ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
