// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_protos/sbai_protos/event_annotation_service.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { TagEventRequest, TagEventResponse } from "../../../sbai_protos/tag_event";

export const protobufPackage = "sbai_protos";

export type EventAnnotationServiceService = typeof EventAnnotationServiceService;
export const EventAnnotationServiceService = {
  tagEvent: {
    path: "/sbai_protos.EventAnnotationService/TagEvent",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: TagEventRequest) => Buffer.from(TagEventRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => TagEventRequest.decode(value),
    responseSerialize: (value: TagEventResponse) => Buffer.from(TagEventResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => TagEventResponse.decode(value),
  },
} as const;

export interface EventAnnotationServiceServer extends UntypedServiceImplementation {
  tagEvent: handleUnaryCall<TagEventRequest, TagEventResponse>;
}

export interface EventAnnotationServiceClient extends Client {
  tagEvent(
    request: TagEventRequest,
    callback: (error: ServiceError | null, response: TagEventResponse) => void,
  ): ClientUnaryCall;
  tagEvent(
    request: TagEventRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: TagEventResponse) => void,
  ): ClientUnaryCall;
  tagEvent(
    request: TagEventRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: TagEventResponse) => void,
  ): ClientUnaryCall;
}

export const EventAnnotationServiceClient = makeGenericClientConstructor(
  EventAnnotationServiceService,
  "sbai_protos.EventAnnotationService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): EventAnnotationServiceClient;
  service: typeof EventAnnotationServiceService;
  serviceName: string;
};
