// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_protos/sbai_protos/gps_status.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sbai_protos";

export enum GpsState {
  GPS_STATE_UNSPECIFIED = 0,
  GPS_STATE_INITIALIZING = 1,
  GPS_STATE_READY = 2,
  UNRECOGNIZED = -1,
}

export function gpsStateFromJSON(object: any): GpsState {
  switch (object) {
    case 0:
    case "GPS_STATE_UNSPECIFIED":
      return GpsState.GPS_STATE_UNSPECIFIED;
    case 1:
    case "GPS_STATE_INITIALIZING":
      return GpsState.GPS_STATE_INITIALIZING;
    case 2:
    case "GPS_STATE_READY":
      return GpsState.GPS_STATE_READY;
    case -1:
    case "UNRECOGNIZED":
    default:
      return GpsState.UNRECOGNIZED;
  }
}

export function gpsStateToJSON(object: GpsState): string {
  switch (object) {
    case GpsState.GPS_STATE_UNSPECIFIED:
      return "GPS_STATE_UNSPECIFIED";
    case GpsState.GPS_STATE_INITIALIZING:
      return "GPS_STATE_INITIALIZING";
    case GpsState.GPS_STATE_READY:
      return "GPS_STATE_READY";
    case GpsState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface GpsStatus {
  gpsState: GpsState;
}

function createBaseGpsStatus(): GpsStatus {
  return { gpsState: 0 };
}

export const GpsStatus: MessageFns<GpsStatus> = {
  encode(message: GpsStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.gpsState !== 0) {
      writer.uint32(8).int32(message.gpsState);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GpsStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGpsStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.gpsState = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GpsStatus {
    return { gpsState: isSet(object.gpsState) ? gpsStateFromJSON(object.gpsState) : 0 };
  },

  toJSON(message: GpsStatus): unknown {
    const obj: any = {};
    if (message.gpsState !== 0) {
      obj.gpsState = gpsStateToJSON(message.gpsState);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GpsStatus>, I>>(base?: I): GpsStatus {
    return GpsStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GpsStatus>, I>>(object: I): GpsStatus {
    const message = createBaseGpsStatus();
    message.gpsState = object.gpsState ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
