// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_protos/sbai_protos/multi_waypoint_navigation_parameters.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sbai_protos";

export interface MultiWaypointNavigationParameters {
  desiredFinalYawDeg: number;
}

function createBaseMultiWaypointNavigationParameters(): MultiWaypointNavigationParameters {
  return { desiredFinalYawDeg: 0 };
}

export const MultiWaypointNavigationParameters: MessageFns<MultiWaypointNavigationParameters> = {
  encode(message: MultiWaypointNavigationParameters, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.desiredFinalYawDeg !== 0) {
      writer.uint32(21).float(message.desiredFinalYawDeg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MultiWaypointNavigationParameters {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMultiWaypointNavigationParameters();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.desiredFinalYawDeg = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MultiWaypointNavigationParameters {
    return { desiredFinalYawDeg: isSet(object.desiredFinalYawDeg) ? globalThis.Number(object.desiredFinalYawDeg) : 0 };
  },

  toJSON(message: MultiWaypointNavigationParameters): unknown {
    const obj: any = {};
    if (message.desiredFinalYawDeg !== 0) {
      obj.desiredFinalYawDeg = message.desiredFinalYawDeg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MultiWaypointNavigationParameters>, I>>(
    base?: I,
  ): MultiWaypointNavigationParameters {
    return MultiWaypointNavigationParameters.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MultiWaypointNavigationParameters>, I>>(
    object: I,
  ): MultiWaypointNavigationParameters {
    const message = createBaseMultiWaypointNavigationParameters();
    message.desiredFinalYawDeg = object.desiredFinalYawDeg ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
