// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_protos/sbai_protos/navigate_to.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { GeoPoint } from "../../../sbai_protos/geo_point";
import { RequestHeader } from "../../../sbai_protos/request_header";

export const protobufPackage = "sbai_protos";

export interface NavigateToRequest {
  header: RequestHeader | undefined;
  behaviorRequestId: string;
  participatingRobotId: string;
  geoPoints: GeoPoint[];
  desiredFinalYawDeg: number;
}

export interface NavigateToResponse {
  queuedSuccessfully: boolean;
}

function createBaseNavigateToRequest(): NavigateToRequest {
  return { header: undefined, behaviorRequestId: "", participatingRobotId: "", geoPoints: [], desiredFinalYawDeg: 0 };
}

export const NavigateToRequest: MessageFns<NavigateToRequest> = {
  encode(message: NavigateToRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.header !== undefined) {
      RequestHeader.encode(message.header, writer.uint32(10).fork()).join();
    }
    if (message.behaviorRequestId !== "") {
      writer.uint32(18).string(message.behaviorRequestId);
    }
    if (message.participatingRobotId !== "") {
      writer.uint32(26).string(message.participatingRobotId);
    }
    for (const v of message.geoPoints) {
      GeoPoint.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.desiredFinalYawDeg !== 0) {
      writer.uint32(45).float(message.desiredFinalYawDeg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NavigateToRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNavigateToRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.header = RequestHeader.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.behaviorRequestId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.participatingRobotId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.geoPoints.push(GeoPoint.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.desiredFinalYawDeg = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NavigateToRequest {
    return {
      header: isSet(object.header) ? RequestHeader.fromJSON(object.header) : undefined,
      behaviorRequestId: isSet(object.behaviorRequestId) ? globalThis.String(object.behaviorRequestId) : "",
      participatingRobotId: isSet(object.participatingRobotId) ? globalThis.String(object.participatingRobotId) : "",
      geoPoints: globalThis.Array.isArray(object?.geoPoints)
        ? object.geoPoints.map((e: any) => GeoPoint.fromJSON(e))
        : [],
      desiredFinalYawDeg: isSet(object.desiredFinalYawDeg) ? globalThis.Number(object.desiredFinalYawDeg) : 0,
    };
  },

  toJSON(message: NavigateToRequest): unknown {
    const obj: any = {};
    if (message.header !== undefined) {
      obj.header = RequestHeader.toJSON(message.header);
    }
    if (message.behaviorRequestId !== "") {
      obj.behaviorRequestId = message.behaviorRequestId;
    }
    if (message.participatingRobotId !== "") {
      obj.participatingRobotId = message.participatingRobotId;
    }
    if (message.geoPoints?.length) {
      obj.geoPoints = message.geoPoints.map((e) => GeoPoint.toJSON(e));
    }
    if (message.desiredFinalYawDeg !== 0) {
      obj.desiredFinalYawDeg = message.desiredFinalYawDeg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NavigateToRequest>, I>>(base?: I): NavigateToRequest {
    return NavigateToRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NavigateToRequest>, I>>(object: I): NavigateToRequest {
    const message = createBaseNavigateToRequest();
    message.header = (object.header !== undefined && object.header !== null)
      ? RequestHeader.fromPartial(object.header)
      : undefined;
    message.behaviorRequestId = object.behaviorRequestId ?? "";
    message.participatingRobotId = object.participatingRobotId ?? "";
    message.geoPoints = object.geoPoints?.map((e) => GeoPoint.fromPartial(e)) || [];
    message.desiredFinalYawDeg = object.desiredFinalYawDeg ?? 0;
    return message;
  },
};

function createBaseNavigateToResponse(): NavigateToResponse {
  return { queuedSuccessfully: false };
}

export const NavigateToResponse: MessageFns<NavigateToResponse> = {
  encode(message: NavigateToResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.queuedSuccessfully !== false) {
      writer.uint32(8).bool(message.queuedSuccessfully);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NavigateToResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNavigateToResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.queuedSuccessfully = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NavigateToResponse {
    return {
      queuedSuccessfully: isSet(object.queuedSuccessfully) ? globalThis.Boolean(object.queuedSuccessfully) : false,
    };
  },

  toJSON(message: NavigateToResponse): unknown {
    const obj: any = {};
    if (message.queuedSuccessfully !== false) {
      obj.queuedSuccessfully = message.queuedSuccessfully;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NavigateToResponse>, I>>(base?: I): NavigateToResponse {
    return NavigateToResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NavigateToResponse>, I>>(object: I): NavigateToResponse {
    const message = createBaseNavigateToResponse();
    message.queuedSuccessfully = object.queuedSuccessfully ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
