// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_protos/sbai_protos/oak_status.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sbai_protos";

export enum OakState {
  OAK_STATE_UNSPECIFIED = 0,
  OAK_STATE_NORMAL = 1,
  OAK_STATE_ERROR = 2,
  UNRECOGNIZED = -1,
}

export function oakStateFromJSON(object: any): OakState {
  switch (object) {
    case 0:
    case "OAK_STATE_UNSPECIFIED":
      return OakState.OAK_STATE_UNSPECIFIED;
    case 1:
    case "OAK_STATE_NORMAL":
      return OakState.OAK_STATE_NORMAL;
    case 2:
    case "OAK_STATE_ERROR":
      return OakState.OAK_STATE_ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OakState.UNRECOGNIZED;
  }
}

export function oakStateToJSON(object: OakState): string {
  switch (object) {
    case OakState.OAK_STATE_UNSPECIFIED:
      return "OAK_STATE_UNSPECIFIED";
    case OakState.OAK_STATE_NORMAL:
      return "OAK_STATE_NORMAL";
    case OakState.OAK_STATE_ERROR:
      return "OAK_STATE_ERROR";
    case OakState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface OakStatus {
  oakState: OakState;
}

function createBaseOakStatus(): OakStatus {
  return { oakState: 0 };
}

export const OakStatus: MessageFns<OakStatus> = {
  encode(message: OakStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.oakState !== 0) {
      writer.uint32(8).int32(message.oakState);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OakStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOakStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.oakState = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OakStatus {
    return { oakState: isSet(object.oakState) ? oakStateFromJSON(object.oakState) : 0 };
  },

  toJSON(message: OakStatus): unknown {
    const obj: any = {};
    if (message.oakState !== 0) {
      obj.oakState = oakStateToJSON(message.oakState);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OakStatus>, I>>(base?: I): OakStatus {
    return OakStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OakStatus>, I>>(object: I): OakStatus {
    const message = createBaseOakStatus();
    message.oakState = object.oakState ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
