// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_protos/sbai_protos/patrol_request.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { GeoPoint } from "../../../sbai_protos/geo_point";

export const protobufPackage = "sbai_protos";

export interface PatrolRequest {
  behaviorRequestId: string;
  participatingRobotIds: string[];
  patrolPerimeterPoints: GeoPoint[];
}

function createBasePatrolRequest(): PatrolRequest {
  return { behaviorRequestId: "", participatingRobotIds: [], patrolPerimeterPoints: [] };
}

export const PatrolRequest: MessageFns<PatrolRequest> = {
  encode(message: PatrolRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.behaviorRequestId !== "") {
      writer.uint32(10).string(message.behaviorRequestId);
    }
    for (const v of message.participatingRobotIds) {
      writer.uint32(18).string(v!);
    }
    for (const v of message.patrolPerimeterPoints) {
      GeoPoint.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PatrolRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePatrolRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.behaviorRequestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.participatingRobotIds.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.patrolPerimeterPoints.push(GeoPoint.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PatrolRequest {
    return {
      behaviorRequestId: isSet(object.behaviorRequestId) ? globalThis.String(object.behaviorRequestId) : "",
      participatingRobotIds: globalThis.Array.isArray(object?.participatingRobotIds)
        ? object.participatingRobotIds.map((e: any) => globalThis.String(e))
        : [],
      patrolPerimeterPoints: globalThis.Array.isArray(object?.patrolPerimeterPoints)
        ? object.patrolPerimeterPoints.map((e: any) => GeoPoint.fromJSON(e))
        : [],
    };
  },

  toJSON(message: PatrolRequest): unknown {
    const obj: any = {};
    if (message.behaviorRequestId !== "") {
      obj.behaviorRequestId = message.behaviorRequestId;
    }
    if (message.participatingRobotIds?.length) {
      obj.participatingRobotIds = message.participatingRobotIds;
    }
    if (message.patrolPerimeterPoints?.length) {
      obj.patrolPerimeterPoints = message.patrolPerimeterPoints.map((e) => GeoPoint.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PatrolRequest>, I>>(base?: I): PatrolRequest {
    return PatrolRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PatrolRequest>, I>>(object: I): PatrolRequest {
    const message = createBasePatrolRequest();
    message.behaviorRequestId = object.behaviorRequestId ?? "";
    message.participatingRobotIds = object.participatingRobotIds?.map((e) => e) || [];
    message.patrolPerimeterPoints = object.patrolPerimeterPoints?.map((e) => GeoPoint.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
