// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_protos/sbai_protos/payload_service.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { BoolValue } from "../../../google/protobuf/wrappers";
import { BoomButtonCommand } from "../../../sbai_protos/boom_button_command";
import { PayloadIdentity } from "../../../sbai_protos/payload_identity";

export const protobufPackage = "sbai_protos";

export type PayloadServiceService = typeof PayloadServiceService;
export const PayloadServiceService = {
  registerPayload: {
    path: "/sbai_protos.PayloadService/RegisterPayload",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: PayloadIdentity) => Buffer.from(PayloadIdentity.encode(value).finish()),
    requestDeserialize: (value: Buffer) => PayloadIdentity.decode(value),
    responseSerialize: (value: boolean | undefined) =>
      Buffer.from(BoolValue.encode({ value: value ?? false }).finish()),
    responseDeserialize: (value: Buffer) => BoolValue.decode(value).value,
  },
  triggerBoom: {
    path: "/sbai_protos.PayloadService/TriggerBoom",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: BoomButtonCommand) => Buffer.from(BoomButtonCommand.encode(value).finish()),
    requestDeserialize: (value: Buffer) => BoomButtonCommand.decode(value),
    responseSerialize: (value: boolean | undefined) =>
      Buffer.from(BoolValue.encode({ value: value ?? false }).finish()),
    responseDeserialize: (value: Buffer) => BoolValue.decode(value).value,
  },
} as const;

export interface PayloadServiceServer extends UntypedServiceImplementation {
  registerPayload: handleUnaryCall<PayloadIdentity, boolean | undefined>;
  triggerBoom: handleUnaryCall<BoomButtonCommand, boolean | undefined>;
}

export interface PayloadServiceClient extends Client {
  registerPayload(
    request: PayloadIdentity,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  registerPayload(
    request: PayloadIdentity,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  registerPayload(
    request: PayloadIdentity,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  triggerBoom(
    request: BoomButtonCommand,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  triggerBoom(
    request: BoomButtonCommand,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
  triggerBoom(
    request: BoomButtonCommand,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: boolean | undefined) => void,
  ): ClientUnaryCall;
}

export const PayloadServiceClient = makeGenericClientConstructor(
  PayloadServiceService,
  "sbai_protos.PayloadService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): PayloadServiceClient;
  service: typeof PayloadServiceService;
  serviceName: string;
};
