// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_protos/sbai_protos/rally_to.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { GeoPoint } from "../../../sbai_protos/geo_point";
import { RequestHeader } from "../../../sbai_protos/request_header";

export const protobufPackage = "sbai_protos";

export interface RallyToRequest {
  header: RequestHeader | undefined;
  behaviorRequestId: string;
  participatingRobotIds: string[];
  geoPoint: GeoPoint | undefined;
  rallyPointToleranceM: number;
}

export interface RallyToResponse {
  queuedSuccessfully: boolean;
}

function createBaseRallyToRequest(): RallyToRequest {
  return {
    header: undefined,
    behaviorRequestId: "",
    participatingRobotIds: [],
    geoPoint: undefined,
    rallyPointToleranceM: 0,
  };
}

export const RallyToRequest: MessageFns<RallyToRequest> = {
  encode(message: RallyToRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.header !== undefined) {
      RequestHeader.encode(message.header, writer.uint32(10).fork()).join();
    }
    if (message.behaviorRequestId !== "") {
      writer.uint32(18).string(message.behaviorRequestId);
    }
    for (const v of message.participatingRobotIds) {
      writer.uint32(26).string(v!);
    }
    if (message.geoPoint !== undefined) {
      GeoPoint.encode(message.geoPoint, writer.uint32(34).fork()).join();
    }
    if (message.rallyPointToleranceM !== 0) {
      writer.uint32(45).float(message.rallyPointToleranceM);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RallyToRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRallyToRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.header = RequestHeader.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.behaviorRequestId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.participatingRobotIds.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.geoPoint = GeoPoint.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.rallyPointToleranceM = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RallyToRequest {
    return {
      header: isSet(object.header) ? RequestHeader.fromJSON(object.header) : undefined,
      behaviorRequestId: isSet(object.behaviorRequestId) ? globalThis.String(object.behaviorRequestId) : "",
      participatingRobotIds: globalThis.Array.isArray(object?.participatingRobotIds)
        ? object.participatingRobotIds.map((e: any) => globalThis.String(e))
        : [],
      geoPoint: isSet(object.geoPoint) ? GeoPoint.fromJSON(object.geoPoint) : undefined,
      rallyPointToleranceM: isSet(object.rallyPointToleranceM) ? globalThis.Number(object.rallyPointToleranceM) : 0,
    };
  },

  toJSON(message: RallyToRequest): unknown {
    const obj: any = {};
    if (message.header !== undefined) {
      obj.header = RequestHeader.toJSON(message.header);
    }
    if (message.behaviorRequestId !== "") {
      obj.behaviorRequestId = message.behaviorRequestId;
    }
    if (message.participatingRobotIds?.length) {
      obj.participatingRobotIds = message.participatingRobotIds;
    }
    if (message.geoPoint !== undefined) {
      obj.geoPoint = GeoPoint.toJSON(message.geoPoint);
    }
    if (message.rallyPointToleranceM !== 0) {
      obj.rallyPointToleranceM = message.rallyPointToleranceM;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RallyToRequest>, I>>(base?: I): RallyToRequest {
    return RallyToRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RallyToRequest>, I>>(object: I): RallyToRequest {
    const message = createBaseRallyToRequest();
    message.header = (object.header !== undefined && object.header !== null)
      ? RequestHeader.fromPartial(object.header)
      : undefined;
    message.behaviorRequestId = object.behaviorRequestId ?? "";
    message.participatingRobotIds = object.participatingRobotIds?.map((e) => e) || [];
    message.geoPoint = (object.geoPoint !== undefined && object.geoPoint !== null)
      ? GeoPoint.fromPartial(object.geoPoint)
      : undefined;
    message.rallyPointToleranceM = object.rallyPointToleranceM ?? 0;
    return message;
  },
};

function createBaseRallyToResponse(): RallyToResponse {
  return { queuedSuccessfully: false };
}

export const RallyToResponse: MessageFns<RallyToResponse> = {
  encode(message: RallyToResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.queuedSuccessfully !== false) {
      writer.uint32(8).bool(message.queuedSuccessfully);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RallyToResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRallyToResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.queuedSuccessfully = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RallyToResponse {
    return {
      queuedSuccessfully: isSet(object.queuedSuccessfully) ? globalThis.Boolean(object.queuedSuccessfully) : false,
    };
  },

  toJSON(message: RallyToResponse): unknown {
    const obj: any = {};
    if (message.queuedSuccessfully !== false) {
      obj.queuedSuccessfully = message.queuedSuccessfully;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RallyToResponse>, I>>(base?: I): RallyToResponse {
    return RallyToResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RallyToResponse>, I>>(object: I): RallyToResponse {
    const message = createBaseRallyToResponse();
    message.queuedSuccessfully = object.queuedSuccessfully ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
