// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_protos/sbai_protos/trigger_boom.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { BoomButtonCommand } from "../../../sbai_protos/boom_button_command";
import { RequestHeader } from "../../../sbai_protos/request_header";

export const protobufPackage = "sbai_protos";

export interface TriggerBoomRequest {
  /** Header for the request. */
  header:
    | RequestHeader
    | undefined;
  /** Command to engage the boom button. */
  boomButtonCommand: BoomButtonCommand | undefined;
}

export interface TriggerBoomResponse {
  /** True if the boom button was triggered successfully. */
  success: boolean;
  /** Error message if triggering boom button failed. */
  errorMessage: string;
}

function createBaseTriggerBoomRequest(): TriggerBoomRequest {
  return { header: undefined, boomButtonCommand: undefined };
}

export const TriggerBoomRequest: MessageFns<TriggerBoomRequest> = {
  encode(message: TriggerBoomRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.header !== undefined) {
      RequestHeader.encode(message.header, writer.uint32(10).fork()).join();
    }
    if (message.boomButtonCommand !== undefined) {
      BoomButtonCommand.encode(message.boomButtonCommand, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TriggerBoomRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTriggerBoomRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.header = RequestHeader.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.boomButtonCommand = BoomButtonCommand.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TriggerBoomRequest {
    return {
      header: isSet(object.header) ? RequestHeader.fromJSON(object.header) : undefined,
      boomButtonCommand: isSet(object.boomButtonCommand)
        ? BoomButtonCommand.fromJSON(object.boomButtonCommand)
        : undefined,
    };
  },

  toJSON(message: TriggerBoomRequest): unknown {
    const obj: any = {};
    if (message.header !== undefined) {
      obj.header = RequestHeader.toJSON(message.header);
    }
    if (message.boomButtonCommand !== undefined) {
      obj.boomButtonCommand = BoomButtonCommand.toJSON(message.boomButtonCommand);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TriggerBoomRequest>, I>>(base?: I): TriggerBoomRequest {
    return TriggerBoomRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TriggerBoomRequest>, I>>(object: I): TriggerBoomRequest {
    const message = createBaseTriggerBoomRequest();
    message.header = (object.header !== undefined && object.header !== null)
      ? RequestHeader.fromPartial(object.header)
      : undefined;
    message.boomButtonCommand = (object.boomButtonCommand !== undefined && object.boomButtonCommand !== null)
      ? BoomButtonCommand.fromPartial(object.boomButtonCommand)
      : undefined;
    return message;
  },
};

function createBaseTriggerBoomResponse(): TriggerBoomResponse {
  return { success: false, errorMessage: "" };
}

export const TriggerBoomResponse: MessageFns<TriggerBoomResponse> = {
  encode(message: TriggerBoomResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.errorMessage !== "") {
      writer.uint32(18).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TriggerBoomResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTriggerBoomResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TriggerBoomResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      errorMessage: isSet(object.errorMessage) ? globalThis.String(object.errorMessage) : "",
    };
  },

  toJSON(message: TriggerBoomResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TriggerBoomResponse>, I>>(base?: I): TriggerBoomResponse {
    return TriggerBoomResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TriggerBoomResponse>, I>>(object: I): TriggerBoomResponse {
    const message = createBaseTriggerBoomResponse();
    message.success = object.success ?? false;
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
