// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: sbai_task_assignment_protos/task_assignment_status.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sbai_task_assignment_protos";

/** Must match that of sbai_task_assignment_interfaces::TaskAssignmentStatus.msg */
export enum Status {
  STATUS_UNKNOWN = 0,
  STATUS_IDLE = 1,
  STATUS_RUNNING = 2,
  STATUS_FAILED = 3,
  STATUS_SUCCEEDED = 4,
  UNRECOGNIZED = -1,
}

export function statusFromJSON(object: any): Status {
  switch (object) {
    case 0:
    case "STATUS_UNKNOWN":
      return Status.STATUS_UNKNOWN;
    case 1:
    case "STATUS_IDLE":
      return Status.STATUS_IDLE;
    case 2:
    case "STATUS_RUNNING":
      return Status.STATUS_RUNNING;
    case 3:
    case "STATUS_FAILED":
      return Status.STATUS_FAILED;
    case 4:
    case "STATUS_SUCCEEDED":
      return Status.STATUS_SUCCEEDED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Status.UNRECOGNIZED;
  }
}

export function statusToJSON(object: Status): string {
  switch (object) {
    case Status.STATUS_UNKNOWN:
      return "STATUS_UNKNOWN";
    case Status.STATUS_IDLE:
      return "STATUS_IDLE";
    case Status.STATUS_RUNNING:
      return "STATUS_RUNNING";
    case Status.STATUS_FAILED:
      return "STATUS_FAILED";
    case Status.STATUS_SUCCEEDED:
      return "STATUS_SUCCEEDED";
    case Status.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface TaskAssignmentStatus {
  behaviorRequestId: string;
  status: Status;
}

function createBaseTaskAssignmentStatus(): TaskAssignmentStatus {
  return { behaviorRequestId: "", status: 0 };
}

export const TaskAssignmentStatus: MessageFns<TaskAssignmentStatus> = {
  encode(message: TaskAssignmentStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.behaviorRequestId !== "") {
      writer.uint32(10).string(message.behaviorRequestId);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TaskAssignmentStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskAssignmentStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.behaviorRequestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskAssignmentStatus {
    return {
      behaviorRequestId: isSet(object.behaviorRequestId) ? globalThis.String(object.behaviorRequestId) : "",
      status: isSet(object.status) ? statusFromJSON(object.status) : 0,
    };
  },

  toJSON(message: TaskAssignmentStatus): unknown {
    const obj: any = {};
    if (message.behaviorRequestId !== "") {
      obj.behaviorRequestId = message.behaviorRequestId;
    }
    if (message.status !== 0) {
      obj.status = statusToJSON(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TaskAssignmentStatus>, I>>(base?: I): TaskAssignmentStatus {
    return TaskAssignmentStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TaskAssignmentStatus>, I>>(object: I): TaskAssignmentStatus {
    const message = createBaseTaskAssignmentStatus();
    message.behaviorRequestId = object.behaviorRequestId ?? "";
    message.status = object.status ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
