// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: sbai_task_assignment_protos/update_iteration.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sbai_task_assignment_protos";

export interface UpdateIteration {
  robotId: string;
  updateIteration: number;
}

function createBaseUpdateIteration(): UpdateIteration {
  return { robotId: "", updateIteration: 0 };
}

export const UpdateIteration: MessageFns<UpdateIteration> = {
  encode(message: UpdateIteration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.robotId !== "") {
      writer.uint32(10).string(message.robotId);
    }
    if (message.updateIteration !== 0) {
      writer.uint32(16).int32(message.updateIteration);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateIteration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateIteration();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.robotId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.updateIteration = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateIteration {
    return {
      robotId: isSet(object.robotId) ? globalThis.String(object.robotId) : "",
      updateIteration: isSet(object.updateIteration) ? globalThis.Number(object.updateIteration) : 0,
    };
  },

  toJSON(message: UpdateIteration): unknown {
    const obj: any = {};
    if (message.robotId !== "") {
      obj.robotId = message.robotId;
    }
    if (message.updateIteration !== 0) {
      obj.updateIteration = Math.round(message.updateIteration);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateIteration>, I>>(base?: I): UpdateIteration {
    return UpdateIteration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateIteration>, I>>(object: I): UpdateIteration {
    const message = createBaseUpdateIteration();
    message.robotId = object.robotId ?? "";
    message.updateIteration = object.updateIteration ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
