// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_swarm_protos/sbai_swarm_protos/cbba_consensus_data_sbai.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { String } from "../../../sbai_std_protos/string";
import { CBBAConsensusData } from "../../../sbai_task_assignment_protos/cbba_consensus_data";

export const protobufPackage = "sbai_swarm_protos";

export interface CBBAConsensusDataSBAI {
  robotId: String | undefined;
  data: CBBAConsensusData | undefined;
}

function createBaseCBBAConsensusDataSBAI(): CBBAConsensusDataSBAI {
  return { robotId: undefined, data: undefined };
}

export const CBBAConsensusDataSBAI: MessageFns<CBBAConsensusDataSBAI> = {
  encode(message: CBBAConsensusDataSBAI, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.robotId !== undefined) {
      String.encode(message.robotId, writer.uint32(10).fork()).join();
    }
    if (message.data !== undefined) {
      CBBAConsensusData.encode(message.data, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CBBAConsensusDataSBAI {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCBBAConsensusDataSBAI();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.robotId = String.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = CBBAConsensusData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CBBAConsensusDataSBAI {
    return {
      robotId: isSet(object.robotId) ? String.fromJSON(object.robotId) : undefined,
      data: isSet(object.data) ? CBBAConsensusData.fromJSON(object.data) : undefined,
    };
  },

  toJSON(message: CBBAConsensusDataSBAI): unknown {
    const obj: any = {};
    if (message.robotId !== undefined) {
      obj.robotId = String.toJSON(message.robotId);
    }
    if (message.data !== undefined) {
      obj.data = CBBAConsensusData.toJSON(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CBBAConsensusDataSBAI>, I>>(base?: I): CBBAConsensusDataSBAI {
    return CBBAConsensusDataSBAI.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CBBAConsensusDataSBAI>, I>>(object: I): CBBAConsensusDataSBAI {
    const message = createBaseCBBAConsensusDataSBAI();
    message.robotId = (object.robotId !== undefined && object.robotId !== null)
      ? String.fromPartial(object.robotId)
      : undefined;
    message.data = (object.data !== undefined && object.data !== null)
      ? CBBAConsensusData.fromPartial(object.data)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
