// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: ros2_interfaces/sbai_task_assignment_protos/sbai_task_assignment_protos/winning_bid.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sbai_task_assignment_protos";

export interface WinningBid {
  taskId: number;
  bidValue: number;
}

function createBaseWinningBid(): WinningBid {
  return { taskId: 0, bidValue: 0 };
}

export const WinningBid: MessageFns<WinningBid> = {
  encode(message: WinningBid, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskId !== 0) {
      writer.uint32(8).int32(message.taskId);
    }
    if (message.bidValue !== 0) {
      writer.uint32(21).float(message.bidValue);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WinningBid {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWinningBid();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.taskId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.bidValue = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WinningBid {
    return {
      taskId: isSet(object.taskId) ? globalThis.Number(object.taskId) : 0,
      bidValue: isSet(object.bidValue) ? globalThis.Number(object.bidValue) : 0,
    };
  },

  toJSON(message: WinningBid): unknown {
    const obj: any = {};
    if (message.taskId !== 0) {
      obj.taskId = Math.round(message.taskId);
    }
    if (message.bidValue !== 0) {
      obj.bidValue = message.bidValue;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WinningBid>, I>>(base?: I): WinningBid {
    return WinningBid.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WinningBid>, I>>(object: I): WinningBid {
    const message = createBaseWinningBid();
    message.taskId = object.taskId ?? 0;
    message.bidValue = object.bidValue ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
