// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: sbai_protos/cortex_state_update.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sbai_protos";

export enum CortexState {
  CORTEX_STATE_UNSPECIFIED = 0,
  CORTEX_STATE_INIT = 1,
  CORTEX_STATE_STANDBY = 2,
  CORTEX_STATE_TELEOP = 3,
  CORTEX_STATE_AUTO = 4,
  UNRECOGNIZED = -1,
}

export function cortexStateFromJSON(object: any): CortexState {
  switch (object) {
    case 0:
    case "CORTEX_STATE_UNSPECIFIED":
      return CortexState.CORTEX_STATE_UNSPECIFIED;
    case 1:
    case "CORTEX_STATE_INIT":
      return CortexState.CORTEX_STATE_INIT;
    case 2:
    case "CORTEX_STATE_STANDBY":
      return CortexState.CORTEX_STATE_STANDBY;
    case 3:
    case "CORTEX_STATE_TELEOP":
      return CortexState.CORTEX_STATE_TELEOP;
    case 4:
    case "CORTEX_STATE_AUTO":
      return CortexState.CORTEX_STATE_AUTO;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CortexState.UNRECOGNIZED;
  }
}

export function cortexStateToJSON(object: CortexState): string {
  switch (object) {
    case CortexState.CORTEX_STATE_UNSPECIFIED:
      return "CORTEX_STATE_UNSPECIFIED";
    case CortexState.CORTEX_STATE_INIT:
      return "CORTEX_STATE_INIT";
    case CortexState.CORTEX_STATE_STANDBY:
      return "CORTEX_STATE_STANDBY";
    case CortexState.CORTEX_STATE_TELEOP:
      return "CORTEX_STATE_TELEOP";
    case CortexState.CORTEX_STATE_AUTO:
      return "CORTEX_STATE_AUTO";
    case CortexState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CortexStateUpdate {
  newState: CortexState;
}

function createBaseCortexStateUpdate(): CortexStateUpdate {
  return { newState: 0 };
}

export const CortexStateUpdate: MessageFns<CortexStateUpdate> = {
  encode(message: CortexStateUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.newState !== 0) {
      writer.uint32(8).int32(message.newState);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CortexStateUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCortexStateUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.newState = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CortexStateUpdate {
    return { newState: isSet(object.newState) ? cortexStateFromJSON(object.newState) : 0 };
  },

  toJSON(message: CortexStateUpdate): unknown {
    const obj: any = {};
    if (message.newState !== 0) {
      obj.newState = cortexStateToJSON(message.newState);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CortexStateUpdate>, I>>(base?: I): CortexStateUpdate {
    return CortexStateUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CortexStateUpdate>, I>>(object: I): CortexStateUpdate {
    const message = createBaseCortexStateUpdate();
    message.newState = object.newState ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
