// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: sbai_protos/direct_control_command.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Joystick } from "./joystick";

export const protobufPackage = "sbai_protos";

export interface DirectControlCommand {
  directControlToken: string;
  joy: Joystick | undefined;
}

function createBaseDirectControlCommand(): DirectControlCommand {
  return { directControlToken: "", joy: undefined };
}

export const DirectControlCommand: MessageFns<DirectControlCommand> = {
  encode(message: DirectControlCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.directControlToken !== "") {
      writer.uint32(10).string(message.directControlToken);
    }
    if (message.joy !== undefined) {
      Joystick.encode(message.joy, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DirectControlCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDirectControlCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.directControlToken = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.joy = Joystick.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DirectControlCommand {
    return {
      directControlToken: isSet(object.directControlToken) ? globalThis.String(object.directControlToken) : "",
      joy: isSet(object.joy) ? Joystick.fromJSON(object.joy) : undefined,
    };
  },

  toJSON(message: DirectControlCommand): unknown {
    const obj: any = {};
    if (message.directControlToken !== "") {
      obj.directControlToken = message.directControlToken;
    }
    if (message.joy !== undefined) {
      obj.joy = Joystick.toJSON(message.joy);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DirectControlCommand>, I>>(base?: I): DirectControlCommand {
    return DirectControlCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DirectControlCommand>, I>>(object: I): DirectControlCommand {
    const message = createBaseDirectControlCommand();
    message.directControlToken = object.directControlToken ?? "";
    message.joy = (object.joy !== undefined && object.joy !== null) ? Joystick.fromPartial(object.joy) : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
